### ISSUE TITLE
Investigate performance of triggerInbox

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos-connect#102]
Refreshing the dataset list on wk.org is painfully slow, because of wkconnect. We should investigate and fix the issue.

**Comment by fm3** [comment]
We determined that the info requests sent to neuroglancer storage all in parallel were very slow when coming from the cloud vm this wkconnect instance was hosted on. We moved it to a different server and now the refresh call is 0.7 s rather than 15 s. While it is still not entirely clear why those requests were so slow in the VM (possibly not truly parallel on single-core machine), let’s close this now and re-open if more problems arise.
